### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by nistake** [Unity-Technologies/AssetGraph#22]
I generated new MyPrefabBuilder, added a new string field, and selected the builder in Graph Editor, then "JSON parse error: Invalid escape character in string." occurred at refreshing.

```
public class MyPrefabBuilder : IPrefabBuilder {
	[SerializeField] private string outputFormat = "{0}_prefab";
	public void OnInspectorGUI (Action onValueChanged) {
		var newText = EditorGUILayout.TextField("prefab name", outputFormat);
		if (newText != outputFormat) {
			outputFormat = newText;
			onValueChanged();
		}
         }
}
```

**Comment by hiroki-o** [comment]
Somewhat fixed in 1.1/release. 
1. You should not see the parse error anymore.
2. Because of the nature of the JsonUtility, you may not save formatted text which interferes with based Json sometimes. In such case, you can use CustomScriptUtility added in v1.1 to Encode/Decode string to save text safely.
