### ISSUE TITLE
View Build Progress state

### ISSUE THREAD

**Issue by guitarrapc** [Unity-Technologies/AssetGraph#24]
There are just a console log to check state of running build. I think it's cool if there are an integrated Build progress view shown in the AssetBundleGraph Window.

Is there any plan to check progress in AssetBundleGraph Node Window?

**Comment by hiroki-o** [comment]
Added to Trello.
https://trello.com/b/x3LtwEWX/assetbundle-graph-tool

In release/1.1 it is bit improved with modal dialog.  This is one of the thing I would like to do somehow, but I have not figured out right way to do progressive update on Unity Editor. 

also, please write issue in bitbucket rather than here from next time :)

https://bitbucket.org/Unity-Technologies/assetbundlegraphtool

**Comment by guitarrapc** [comment]
Appreciate for kind pickup. I will write on bitbucket on next time:)
